# syntax=docker/dockerfile:1
# =============================================================================
# HELIX — multi-stage build.
#
# Stage 1 builds the multi-module Maven reactor with a full JDK. Stage 2 runs
# the resulting jar on a minimal JRE — the build toolchain (Maven, compiler,
# every *-sources.jar Maven downloaded) never reaches the image that ships.
# =============================================================================

# ---------------------------------------------------------------------------
# Stage 1: build
# ---------------------------------------------------------------------------
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /build

# Copy only the POMs first. Docker/BuildKit caches each layer by the hash of
# what was COPYed into it, so as long as no pom.xml changed, this
# `dependency:go-offline` layer is reused verbatim on the next build even
# though every Java file under src/ has changed. Source is copied afterwards,
# specifically so editing a controller doesn't invalidate the dependency
# cache and force re-downloading the internet.
COPY pom.xml .
COPY helix-domain/pom.xml helix-domain/pom.xml
COPY helix-service/pom.xml helix-service/pom.xml
COPY helix-api-rest/pom.xml helix-api-rest/pom.xml
COPY helix-api-soap/pom.xml helix-api-soap/pom.xml
COPY helix-app/pom.xml helix-app/pom.xml

RUN --mount=type=cache,target=/root/.m2 \
    mvn -B -q dependency:go-offline

# Now the sources, and the real build. Unit tests run here (they need no
# Docker-in-Docker and are the same 36 tests `mvn verify` runs on a laptop);
# integration tests are Testcontainers-based and deliberately excluded by the
# default surefire configuration (see pom.xml / docs/ARCHITECTURE.md §6) — a
# container build is exactly the environment they'd need Docker-in-Docker
# for, which is a bad trade for what CI already covers in its own stage.
COPY helix-domain/src helix-domain/src
COPY helix-service/src helix-service/src
COPY helix-api-rest/src helix-api-rest/src
COPY helix-api-soap/src helix-api-soap/src
COPY helix-app/src helix-app/src

RUN --mount=type=cache,target=/root/.m2 \
    mvn -B -q -DskipTests package

# ---------------------------------------------------------------------------
# Stage 2: runtime
# ---------------------------------------------------------------------------
FROM eclipse-temurin:21-jre-alpine AS runtime

# Patch the base image's OS packages before doing anything else.
#
# The Temurin Alpine base is rebuilt on its own cadence, so on any given day
# it can lag the Alpine security repo — that is how CVE-2026-14456 (an OpenSSL
# QUIC-server DoS, fixed in 3.5.8-r0) reaches the Trivy gate even though a fix
# exists. `apk upgrade` pulls the current patched packages at build time, so
# the image ships fixed rather than waiting on a base-image rebuild. The
# scan stays strict (`--ignore-unfixed=false`); this keeps it green honestly.
RUN apk update && apk upgrade --no-cache

# Non-root. A JVM that gets remote-code-execution'd running as root can
# still only do what a low-privilege OS user can do.
RUN addgroup -S helix && adduser -S helix -G helix

WORKDIR /app

# finalName in helix-app/pom.xml is "helix" -> helix-app/target/helix.jar.
COPY --from=build --chown=helix:helix /build/helix-app/target/helix.jar /app/helix.jar

USER helix

EXPOSE 8080

# -----------------------------------------------------------------------
# Why MaxRAMPercentage=75 and not 100:
#
# The container memory limit (set on the Kubernetes Pod / `docker run -m`)
# bounds the WHOLE process's resident memory, not just the Java heap.
# MaxRAMPercentage sizes only the heap. Outside the heap, inside the same
# cgroup limit, the JVM also needs room for:
#   - metaspace (class metadata — grows with the number of loaded classes;
#     Spring's proxies and Hibernate's generated bytecode add a lot of them)
#   - thread stacks (each platform thread reserves ~1MB by default; Tomcat's
#     worker pool and Hikari's connections each carry threads)
#   - the JIT code cache
#   - direct byte buffers and native memory used by the JDBC driver, NIO,
#     and GC bookkeeping itself
#
# Handing the heap 100% of the limit leaves nothing for any of that. The
# process gets OOM-killed by the kernel/cgroup the moment metaspace or a
# thread stack needs to grow, and that kill happens OUTSIDE the JVM, so it
# produces no heap dump, no OutOfMemoryError, no log line — just a
# container that silently restarts. 75% leaves a working margin for
# everything the heap doesn't cover.
#
# +UseG1GC: the default collector on JDK 21 already, set explicitly so it
# does not depend on the base image's default ergonomics.
#
# +ExitOnOutOfMemoryError: if the heap itself is exhausted (a real leak or
# genuine undersizing, not a cgroup mismatch), exit immediately rather than
# limping on with a JVM that just paused the world for a failed collection.
# Kubernetes' restart policy is the correct handler for that, not the
# process trying to survive in a half-broken state.
# -----------------------------------------------------------------------
ENV JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=75 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError"

# Liveness only — no dependency checks (DB, IdP) reach this probe. See
# helm/templates/deployment.yaml for why that separation matters in
# Kubernetes; the same reasoning applies to a bare `docker run`.
HEALTHCHECK --interval=30s --timeout=3s --start-period=90s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health/liveness || exit 1

ENTRYPOINT ["java", "-jar", "/app/helix.jar"]
